# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d08117caf8e80c8de855dc0367c045832ff0bc3e5d13a4d5b7f8e4f20063094a96dcf3cbb92a430000e22b8f9245a1bbde1905fcc04bd4cddfaa144c52c800ab

test:
  secret_key_base: 5710ecbf18c8dd2dc8a4525a3f61161319a4cca500f49c081e9e1bcf10a7c7124f8d0e279ffa3e9c96ec714b9b777435842acfc1db32e5f13689081fc3ae65c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
